version: '3.0'

services:
  simple-client:
    build: SimpleClient
    image: wwupi/simple-client
    ports:
      - "8080:8080"
      - "9990:9990"

  simple-server:
    build: SimpleServer
    image: wwupi/simple-server
    ports:
      - "8081:8080"
      - "9991:9990"
