version: '3.0'

services:
  simple-client:
    build: SimpleClient
    image: wwupi/simple-client
    ports:
      - "8084:8084"
      - "9994:9994"

  simple-server:
    build: SimpleServer
    image: wwupi/simple-server
    ports:
      - "8085:8084"
      - "9995:9994"
